version: '3'

services:
  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command : start 
    environment:
      PYTHONUNBUFFERED: "1"
      DNA_TOKEN: ${DNA_TOKEN}
      MONGODB_URL: ${MONGODB_URL}  # Ensure this is your MongoDB Atlas connection string
      DATABASE_NAME: ${DATABASE_NAME}
      COLLECTION_NAME: ${COLLECTION_NAME}
